apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  name: repo-sync
  namespace: whereami
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/mathieu-benoit/acm-workshop-whereami-repo
    revision: HEAD
    branch: main
    dir: staging
    auth: none
