name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0.5.0
      - name: install kpt and nomos	
        run: |
          gcloud components install kpt nomos --quiet
      - name: install gator
        run: |
          curl -OL https://github.com/open-policy-agent/gatekeeper/releases/download/v${GATOR_VERSION}/gator-v${GATOR_VERSION}-linux-amd64.tar.gz
          tar xvf gator-v${GATOR_VERSION}-linux-amd64.tar.gz && rm gator-v${GATOR_VERSION}-linux-amd64.tar.gz
        env:
          GATOR_VERSION: 3.8.1
      - name: vet	
        run: |
          nomos vet --path . --no-api-server-check --source-format unstructured
      - name: kubeval
        if: ${{ always() }}
        run: |
          kpt fn eval . --results-dir tmp --image gcr.io/kpt-fn/kubeval:v0.3 -- strict=true ignore_missing_schemas=true
      - name: get external templates
        if: ${{ always() }}
        run: |
          kpt pkg get https://github.com/mathieu-benoit/acm-workshop-policies templates
      - name: gatekeeper
        if: ${{ always() }}
        run: |
          kpt fn eval . --results-dir tmp --image gcr.io/kpt-fn/gatekeeper:v0.2
      - name: gator test
        if: ${{ always() }}
        run: |
          rm .github/workflows/ci.yml
          ./gator test -f .
